default_platform(:ios)

platform :ios do
  desc "Build IPA for App Store"
  lane :build_ipa do
    cocoapods
    build_app(
      scheme: "weblah",
      workspace: "weblah.xcworkspace",
      export_method: "app-store",
      output_directory: "../build",
      output_name: "weblah.ipa",
      include_bitcode: false
    )
  end

  desc "Upload latest IPA to TestFlight"
  lane :upload_testflight do
    api_key_obj = nil
    if ENV['ASC_KEY_ID'] && ENV['ASC_ISSUER_ID'] && ENV['ASC_KEY']
      api_key_obj = app_store_connect_api_key(
        key_id: ENV['ASC_KEY_ID'],
        issuer_id: ENV['ASC_ISSUER_ID'],
        key_content: ENV['ASC_KEY'],
        is_key_content_base64: true
      )
    end
    ipa_path = "../build/weblah.ipa"
    if File.exist?(ipa_path)
      upload_to_testflight(api_key: api_key_obj, ipa: ipa_path, distribute_external: false)
    else
      build_ipa
      upload_to_testflight(api_key: api_key_obj, ipa: "../build/weblah.ipa", distribute_external: false)
    end
  end
end
